### ISSUE TITLE
Any Custom Field Breaks with Meteor.js - `Uncaught Invariant Violation: useForm must be used within a form`. 

### ISSUE THREAD

**Issue by mbseid** [vazco/uniforms#1150] opened 2022-07-22 02:17 UTC
While using Meteor.js, any custom field breaks with the error: `Uncaught Invariant Violation: useForm must be used within a form.`. There are a few bug reports around it, mostly related to two things: 
1. Ensuring package are the same ✅
2. Builds during packaging ❓

I'm guessing somewhere in the Meteor process it breaks. 

Attached a branch of the error code, working sandbox, and stack trace.

Broken Code: https://github.com/mbseid/success/tree/brokenCustomField
reproduction steps:
1. npm install -g meteor
2. meteor npm install
3. meteor run
4. open `http://localhost:3000/links/new`

Working Sandbox: https://codesandbox.io/s/frosty-roentgen-7x3is6?file=/ImageField.jsx

Stack Trace:
```
Uncaught Invariant Violation: useForm must be used within a form.
    invariant modules.js:53265
    useForm modules.js:45759
    useField modules.js:45681
    Field modules.js:45635
    renderWithHooks modules.js:21025
    mountIndeterminateComponent modules.js:23851
    beginWork modules.js:25089
    callCallback modules.js:9985
    invokeGuardedCallbackDev modules.js:10034
    invokeGuardedCallback modules.js:10096
    beginWork$1 modules.js:30004
    performUnitOfWork modules.js:28816
    workLoopSync modules.js:28747
    renderRootSync modules.js:28710
    performSyncWorkOnRoot modules.js:28333
    scheduleUpdateOnFiber modules.js:27921
    updateContainer modules.js:31522
    legacyRenderSubtreeIntoContainer modules.js:32061
    unbatchedUpdates modules.js:28471
    legacyRenderSubtreeIntoContainer modules.js:32060
    render modules.js:32143
    module main.jsx:12
    maybeReady meteor.js:943
    loadingCompleted meteor.js:955
    EventListener.handleEvent* meteor.js:970
    <anonymous> meteor.js:1009
    <anonymous> meteor.js:1362
```

**Comment by radekmie** [comment] 2022-07-22 10:38
Hi @mbseid. We successfully use uniforms in Meteor projects, so I'm sure it's not a problem with Meteor itself. I wanted to check your repo but the link says it doesn't exist - maybe it's private?

**Comment by mbseid** [comment] 2022-07-28 01:50
Hey, I just switched the repo to public. Sorry and appreciate y'all looking into it.

**Comment by radekmie** [comment] 2022-08-09 07:58
The problem is, that your `uniforms-mui` has its own copy of `uniforms` ([source](https://github.com/mbseid/success/blob/brokenCustomField/package-lock.json#L1550-L1560)). Running `meteor npm dedupe` solves the issue and the app works. Let me know if that's all.

**Comment by radekmie** [comment] 2022-08-13 11:39
I’ll close this one, but feel free to comment further!

**Closed by radekmie** 2022-08-13 11:39 UTC
Labels: Type: Question
