### ISSUE TITLE
Custom Field

### ISSUE THREAD

**Issue by DavidSichau** [vazco/uniforms#234] opened 2017-03-15 13:13 UTC
I want to add an own field, however I only get error messages from react and no field. I tried out the circle field from the readme and a custom field.

My custom field looks like, it should simply display test:
```
import React from 'react';
import connectField   from 'uniforms/connectField';
const TestField = props => <div>test </div>;
export default connectField(TestField);
```

And my Schema looks like:

```
export const PlansSchema = new SimpleSchema({
    title: {
        type: String,
        max: 200,
    },
    description: {
        type: String,
    },
    testField: {
        type: String,
        uniforms: {
            component: 'TestField',
           // component: 'Cycle', with the Cyle Field from the readme it also does not work.
        },
    },
});
```

The error is like:

```
Warning: Unknown props `changed`, `error`, `errorMessage`, `field`, `fieldType`, `fields`, `findError`, `findField`, `findValue`, `parent`, `changedMap`, `showInlineError`, `grid`, `hintText`, `hintTitle`, `listAdd`, `listDel`, `toggleOptionalLabel` on <TestField> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in TestField (created by Auto)
    in Auto (created by AutoField)
    in AutoField
    in form (created by AutoValidatedQuickBootstrap4Form)
    in AutoValidatedQuickBootstrap4Form (created by NewItem)
    in NewItem (created by Container(NewItem))
    in Container(NewItem) (created by UseDeps(Container(NewItem)))
    in UseDeps(Container(NewItem)) (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithDeps(Layout))
    in WithDeps(Layout)
```

And in my form I see a rendered `testfield` however it is not visible at all. Is there some step I missed.

It would be actually be nice to have in the read me an example for an field which uses asynchonous values from a server for validating the input.

**Comment by janowsiany** [comment] 2017-03-15 13:42
Hello David, the problem is that you need to define your component property as a `Function`, not as a `String`. Consider [this code](https://github.com/vazco/uniforms/blob/3dd84d7e3cbabf02294b3409f264aac88097615a/packages/uniforms-bootstrap4/src/AutoField.js#L15-L36) and note that when `component` property is defined then we call `createElement` function from [React](https://facebook.github.io/react/docs/react-api.html#createelement), behavior of which you can find under mentioned docs href.

Also the message seen in a console is a warning, not an error.

Closing as answer was given, however feel free to comment if you encounter some problems.

**Closed by janowsiany** 2017-03-15 13:42 UTC
Labels: duplicate, question

**Comment by janowsiany** [comment] 2017-03-15 13:48
Check #215 and #216 for examples of custom fields.
