### ISSUE TITLE
TypeError getValidator is not a function

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#788] opened 2020-08-14 17:29 UTC
Hi, with uniforms 3.0.0-rc.3 I get following error:

```
Uncaught TypeError: this.getContextSchema().getValidator is not a function
    ValidatedForm webpack://.../node_modules/uniforms/es6/ValidatedForm.js?:31
    _ webpack://.../node_modules/uniforms-unstyled/es6/ValidatedForm.js?:10
    AutoForm webpack://.../node_modules/uniforms/es6/AutoForm.js?:24
    _ webpack://.../node_modules/uniforms-unstyled/es6/AutoForm.js?:10
```
In debugger I inspected `this.getContextSchema()` and it as methods `getFormValidator()` and `validator()` but not the `getValidator()`. At version 2.6.9 it works correctly.

**Comment by kestarumper** [comment] 2020-08-19 12:39
Hello @mariusrak,
This is probably caused by a **breaking change** which was introduced in [v3.0.0-alpha.3 (2020-05-06)](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v300-alpha3-2020-05-06) (the version you're using). Because `createSchemaBridge` was removed, you should directly pass `Bridge` to the `AutoForm`.

Example:
```javascript
const schema = new MySchemaBridge(mySchema);

...

<AutoForm schema={schema} {...props} />
```

I hope this helps, feel free to ask more questions and if this solves your problem you can close this issue.

**Comment by kestarumper** [comment] 2020-08-26 08:58
I'm closing this issue because there is no activity. Feel free to ask more questions and re-open if needed.

**Closed by kestarumper** 2020-08-26 08:58 UTC
Labels: question

**Comment by mariusrak** [comment] 2020-09-22 21:49
Does this mean, that I'll have to create new bridge for each autoform?
Why such change? The previous design was easier to use - less writing. What advance does this provide?

**Comment by radekmie** [comment] 2020-09-23 06:53
@mariusrak It was simpler only for SimpleSchema. See #718 for motivation.
