### ISSUE TITLE
Error integrating AutoForm 

### ISSUE THREAD

**Issue by fomeboy** [vazco/uniforms#127] opened 2016-11-03 12:58 UTC
I am getting an error when I try to integrate an AutoForm into a react component using Meteor 1.4.2:

modules.js?hash=5bf51b7…:34814Uncaught TypeError: Cannot read property 'getSubfields' of undefined
    at _class.render (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:34814:49)
    at http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:15691:21
    at measureLifeCyclePerf (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:14972:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:15690:27)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:15717:34)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:15259:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:15155:21)
    at Object.mountComponent (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:7985:35)
    at ReactDOMComponent.mountChildren (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:14271:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/packages/modules.js?hash=5bf51b73472032bacf6ebced1844676e6bacbe24:11429:32)

The code I am using is this:

import { Meteor } from 'meteor/meteor'
import React from 'react'
import { AutoForm } from 'uniforms-unstyled'
import { mySchema } from '../../schemas.js'

class Xpto extends React.Component {

constructor (props) {
    super(props)
    this.state = {}
}

render() {
    return (
            <AutoForm schema={mySchema} onSubmit={doc => console.log(doc)}/>
     )
  }
}

**Comment by radekmie** [comment] 2016-11-03 13:05
Duplicate of #117.

**Closed by radekmie** 2016-11-03 13:05 UTC
Labels: duplicate

**Comment by fomeboy** [comment] 2016-11-03 13:17
sorry. didn't see #117

sorted now...tks!
