### ISSUE TITLE
[QUESTION]: uniforms-bridge-graphql GraphQLInputObjectType vs GraphQLObjectType 

### ISSUE THREAD

**Issue by simplecommerce** [vazco/uniforms#805] opened 2020-09-18 11:47 UTC
Hi,

I was using version 2.6.9 previously before upgrading to the recent 3.0.0 rc4 and I have a weird error.

When I use my schema type with the bridge, it gives me this error in my console.

`Error: Cannot use GraphQLInputObjectType "LoginWithPasswordInput" from another module or realm.`

When I did a check of the type in your example and mine it differs, mine is `GraphQLInputObjectType` and the type in your example is `GraphQLObjectType`.

I assume there was a change in the underlying code?

I use `buildClientSchema` from `graphql` utilities in order to build my schema on the client side and then use `schema.getType` but the type returned doesn't seem to be the same as the one in your example.

Am I missing something?

Hope you can help, thanks!

**Comment by radekmie** [comment] 2020-09-18 11:52
Hi @simplecommerce. Using `*InputType` type instead of a _normal_ `*Type` should work just fine. Could you check, which version of `graphql` are you using? Starting in [v3.0.0-rc.3](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v300-rc3-2020-08-13) uniforms will use `graphql@15`. It may be the case that your application resolves a different version.

If it still won't work, please include a stack trace of this error.

**Comment by simplecommerce** [comment] 2020-09-18 11:53
@radekmie Yeah I thought that also, here is what I am using

```
├── graphql@15.3.0
└─┬ uniforms-bridge-graphql@3.0.0-rc.4
  └── graphql@15.3.0  deduped
```

The error is weird I had never seen it before.

**Comment by simplecommerce** [comment] 2020-09-18 11:55
@radekmie don't know if it could be related but one thing I noticed in my logs is that the `astNode` field is undefined in my `Input` or `Post` types, but when I use your example with `buildASTSchema(parse(schema)).getType('Post');`, the `astNode` field is populated.

I don't know if this matters or not

**Comment by simplecommerce** [comment] 2020-09-18 11:57
This is the complete error in my console

```
Uncaught Error: Cannot use GraphQLInputObjectType "LoginWithPasswordInput" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:8697)
    at isInputObjectType (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:20572)
    at modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:176097
    at Array.reduce (<anonymous>)
    at GraphQLBridge.getField (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:176091)
    at GraphQLBridge.memoized [as getField] (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:50428)
    at useField (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:164415)
    at TextField (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:164349)
    at renderWithHooks (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:107603)
    at mountIndeterminateComponent (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:110282)
    at beginWork (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:111396)
    at HTMLUnknownElement.callCallback (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:92988)
    at Object.invokeGuardedCallbackDev (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:93037)
    at invokeGuardedCallback (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:93092)
    at beginWork$1 (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:116003)
    at performUnitOfWork (modules.js?hash=da8eab1cb2712065daa5a2025a547eea7de0e6dd:114954)
```

**Comment by radekmie** [comment] 2020-09-18 11:58
@simplecommerce Maybe try to rebuild `node_modules`? Or even purge both `node_modules` and `package-lock.json` (or your packager equivalent). As I found out, it's most certainly a problem with multiple copies of `graphql` module.

About the `astNode` - we are not using it.

**Comment by simplecommerce** [comment] 2020-09-18 11:59
> @simplecommerce Maybe try to rebuild `node_modules`? Or even purge both `node_modules` and `package-lock.json` (or your packager equivalent). As I found out, it's most certainly a problem with multiple copies of `graphql` module.
> 
> About the `astNode` - we are not using it.

I tried that already unfortunately, removed `node_modules` and `package-lock`, still get the same error, its really odd

**Comment by radekmie** [comment] 2020-09-18 12:00
@simplecommerce Maybe it's your bundler then? As uniforms require only [`graphql/type/definition`](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bridge-graphql/src/GraphQLBridge.ts#L1-L10), try to import it in your app directly. I believe it could be some tree-shaking problem.

**Comment by radekmie** [comment] 2020-09-18 12:14
@simplecommerce Also, are you using some build-time transform for GraphQL? It may be the culprit as well.

**Comment by simplecommerce** [comment] 2020-09-18 12:17
@radekmie I don't think so, all I do on my client end is 

`client.__schema = buildClientSchema({ __schema: window.__APOLLO_CLIENT_SCHEMA__ });`

which grabs my introspect query result and builds it so I can use the schema with my forms.
and then use the `getType` in order to use them.

it was working on the previous version before I actually switched in order to use `useForm`

it is really odd, I am doing some research and tests in order to see why it keeps giving me that error.

I tried "hardcoding" the `LoginWithPasswordInput` with the same example you provided and I still get the same error message, so I am trying to trace down what else is causing it.

**Comment by radekmie** [comment] 2020-09-18 12:23
@simplecommerce OK, do try to find out, what happens. I'll think about how to proceed here.

**Comment by simplecommerce** [comment] 2020-09-18 12:57
@radekmie does this make any sense to you?

![image](https://user-images.githubusercontent.com/31987945/93599862-c1c6f280-f98c-11ea-813a-4c81ed202f2f.png)

It seems to throw an error here because `valueClass.name` and `className` are the same, but I don't get that logic at all and why.

**Comment by simplecommerce** [comment] 2020-09-18 13:03
Hmm I have the same issue here in a test sandbox using your example in the docs.

https://codesandbox.io/s/gifted-forest-6vn7j?file=/src/App.js

**Comment by simplecommerce** [comment] 2020-09-18 14:04
@radekmie I am not sure I understand what I should do, can you show me what I should do in the sandbox?

**Comment by radekmie** [comment] 2020-09-18 14:06
@simplecommerce Well, I'm not sure how to test it. You'd need to somehow force the bundler to use one version only (e.g. disable `.mjs` completely). As I said, I can't see another way to confirm it besides reverting this import.

**Comment by simplecommerce** [comment] 2020-09-18 14:25
@radekmie I think you may be right, I tried doing a copy/paste of the source of the bridge and create my own by changing the import and it seems to load, but now it doesn't seem to catch the errors from the validator function.

https://codesandbox.io/s/gifted-forest-6vn7j

Maybe I did something wrong.

**Comment by radekmie** [comment] 2020-09-18 14:29
@simplecommerce Starting in [v3.0.0-rc.3](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v300-rc3-2020-08-13) you should return the error instead of throwing it. And the fact that it works with a copied source means that the bundling fails. I'll think about it.

**Comment by simplecommerce** [comment] 2020-09-18 14:30
@radekmie Thank you for your help!!

**Comment by radekmie** [comment] 2020-09-23 10:47
@simplecommerce I wanted to confirm what happens locally and I cannot reproduce it locally. I've downloaded your CodeSandbox, installed dependencies, tried started the project (either dev server or production build) and it works. I've tried both npm and yarn. I'm really confused now. Could you prepare a reproduction repo, that I could clone and run locally?

**Comment by simplecommerce** [comment] 2020-09-23 11:15
@radekmie Unfortunately I don't have a local repo that you could test with other than the codesandbox, it was my attempt to test and see if I could reproduce the issue on another repo. The one I had the issue on, is our company project, so I wouldn't be able to create a local repo for that. 

Don't know if this can help.
I use meteorjs 1.11 with node/npm: v12.18.3/6.14.6

It runs on Ubuntu 18.04.1 LTS 18.04.

I don't know if on codesandbox if we can get the info that it builds the repo on?

**Comment by simplecommerce** [comment] 2020-09-23 11:16
@radekmie I will try to see if I can reproduce it using the codesandbox on my end locally.

**Comment by simplecommerce** [comment] 2020-09-23 11:47
@radekmie I downloaded a zip of the codesandbox and did npm install and I am not able to reproduce the error either.
But when I do it on the sandbox or in my project, the error occurs. It is really weird, I assume it has to be very specific in order to happen but I don't know why.

**Comment by radekmie** [comment] 2020-09-30 13:33
@simplecommerce I'm about to release probably the last RC version of v3. I've tried once again, but I'm still not able to reproduce this error. If you can - we'll be more than happy to fix it. Right now, all I can say is that I _think_ it's bundler related (and my previous findings confirm that).

**Comment by GoaGit** [comment] 2020-09-30 13:49
@radekmie I am running into the same issue as @simplecommerce 

I am using Meteor version 1.11

Npm packages:
- uniforms@3.0.0-rc.4
- uniforms-antd@3.0.0-rc.4
- uniforms-bridge-graphql@3.0.0-rc.4",
- graphql version 15.0.0

Schema definition:

```
const schema = `
  type EmailTemplateForm {
    _id:     String!
    content: String!
  }

  # This is required by buildASTSchema
  type Query { anything: ID }
`;
```

![image](https://user-images.githubusercontent.com/10747329/94693708-538f1200-0334-11eb-9f44-7a7dec89616c.png)

I use npm-force-resolutions to ensure everything resolves to graphql version 15.0.0.

**Comment by radekmie** [comment] 2020-09-30 13:51
@GoaGit could you create a reproduction repo that I could clone and work with? That'd be great!

**Comment by simplecommerce** [comment] 2020-09-30 13:52
@radekmie I posted a discussion on codesandbox with the sample app to see if they can help explain why or what the differences are between their live sandbox and the downloaded zip package. Since I am not able to reproduce the issue with that sample app on my end either. I hope it helps hint out what the issue is.

**Comment by GoaGit** [comment] 2020-09-30 16:07
@radekmie I created a [minimal repo](https://github.com/GoaGit/uniforms-graphql) where the issue shows up. You should first install Meteor version 1.11, run `meteor npm install` and the `meteor`.

**Comment by radekmie** [comment] 2020-10-01 06:49
@GoaGit Thank you! I confirm, this repo correctly reproduces this error. I'll keep you posted.

**Comment by simplecommerce** [comment] 2020-10-01 10:54
@radekmie in case it interests you https://github.com/codesandbox/codesandbox-client/discussions/4958#discussioncomment-88390

Seems to be exactly what you've said.

**Comment by simplecommerce** [comment] 2020-10-01 12:32
@radekmie based on the codesandbox finding, I opened up an issue on meteorjs github to see if they can help fix the issue.

**Comment by radekmie** [comment] 2020-10-01 12:33
@simplecommerce Great! Do mention this issue there so others could find it as well.

**Comment by radekmie** [comment] 2020-10-30 12:17
I think we can close this one for now - thanks again for mentioning it in the other issues so others can follow!

**Closed by radekmie** 2020-10-30 12:17 UTC
Labels: question
