### ISSUE TITLE
TypeError: Cannot read property 'getSubfields' of undefined with Meteor release 1.4.2-beta.13

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#117] opened 2016-10-24 09:25 UTC
i tried the new meteor pre-release ( meteor update--release 1.4.2-beta.13) and I get this error on Forms:

"TypeError: Cannot read property 'getSubfields' of undefined" 

It seems to ocure in QuickForm when accessing `this.getChildContextSchema().getSubFields()`, but I only see the compiled code right now and did not track this down.

**Comment by radekmie** [comment] 2016-10-24 17:01
It sounds very weird, but OK - I'll take a look.
Just to be sure - could you share used schema and package versions?

**Comment by radekmie** [comment] 2016-10-24 18:22
As I investigated for a moment now, it seems like `super()` in `constructor` is not doing anything.

**Comment by radekmie** [comment] 2016-10-24 19:57
I give up. For now at least.
After changing every
```
super(...arguments);
```
to
```
console.log('> component');
super(...arguments);
console.log('< component');
```
all I can say is that in 1.4.2 `super`... Is not working. It don't call parent's `constructor`. It's really weird. As this is not ready release yet, I think we should wait for the official release of 1.4.2 and then _(eventually)_ take care of it.

**Comment by macrozone** [comment] 2016-10-24 20:53
yes, super is not called. super strange. I will take also a look tomorrow. I think we should try to track this down and post and issue on meteor before official 1.4.2 is released. Can you reopen?

I did not find anything related on meteor yet, which makes it even weirder

**Comment by radekmie** [comment] 2016-10-24 20:57
Yeah, I've also looked through meteor issues and there's nothing related. I won't have much free time by the end of the week, so go ahead - I'm very curious what's the problem.

**Comment by macrozone** [comment] 2016-10-25 11:43
I found something, but no solution yet: https://github.com/meteor/meteor/issues/7956

**Comment by benjamn** [comment] 2016-10-26 22:23
I think I know how to fix this, but I'm having trouble reproducing it. Can anyone provide a small example app that has this problem?

**Comment by radekmie** [comment] 2016-10-28 22:04
It looks like [this commit](https://github.com/vazco/uniforms/commit/4677ae97afc025f7a6104d6e4a10564ef727e033) _(updating `babel-runtime` version)_ solves this problem in Meteor 1.4.2. It's already released as 1.4.0 _(huh)_.

**Comment by macrozone** [comment] 2016-10-31 09:03
@radekmie : babel runtime should not be in the npm depencencies, so we have no control over that.

meteor  1.4.2.1-beta.0 should fix it, according to https://github.com/meteor/meteor/issues/7956

but i had no luck with my app. So issue is currently not fixed. I need more time to reproduce it with 1.4.2.1-beta.0

**Comment by radekmie** [comment] 2016-10-31 09:05
I've upgraded `demo` project to 1.4.2 and it's working with `uniforms@1.4.0`. Are you still having problems, @macrozone?

**Comment by radekmie** [comment] 2016-10-31 09:43
Well... Now I've upgraded to 1.4.2.1-beta.0 and it's not working. Unluckily after downgrade to 1.4.2 it's not working again...

**Comment by radekmie** [comment] 2016-11-01 10:42
Finally! If you are still having problems, check for `babel-runtime` in your `.meteor/versions`. If it's present, at least `0.1.13` is required. [Source](https://github.com/meteor/meteor/issues/7956#issuecomment-257525102).

Great thanks @macrozone!

**Closed by radekmie** 2016-11-01 10:42 UTC
Labels: bug
