### ISSUE TITLE
Using uniforms for drag 'n drop form generation

### ISSUE THREAD

**Issue by maasha** [vazco/uniforms#379] opened 2017-12-31 10:52 UTC
Would it be possible to mimic the functionality of the fabulous [jQuery formbuilder](https://formbuilder.online/)?

**Comment by radekmie** [comment] 2017-12-31 11:51
Hi @maasha.

Why not? Of course, it is! I'm aware of one open sourced one: [`react-easel`](https://github.com/noahprince22/react-easel). I also worked on two others: the first one was similar to this one, the second one was far more advanced (complex layouts, conditional fields and few more fancy things).

As it's not a bug nor a feature request, I'm closing.

**Closed by radekmie** 2017-12-31 11:51 UTC
Labels: question

**Comment by maasha** [comment] 2017-12-31 12:49
Excellent. I will give it a spin (extensive searching for react formbuilder/formgenerator, etc didn't turn up  react-easel).

**Comment by jy4618272** [comment] 2018-05-19 14:30
@radekmie hi, is the second one open source ? ：)

**Comment by radekmie** [comment] 2018-05-19 14:47
@jy4618272 no, it's not.

**Comment by dmushkov** [comment] 2020-11-02 13:15
@radekmie unfortunate you did not mention which is 'the second one was far more advanced' ... is there any reason for that?

**Comment by radekmie** [comment] 2020-11-05 14:55
Hi @dmushkov. What do you mean _I don't mention it_? It's not an open source one, made for one of our projects.

**Comment by dmushkov** [comment] 2020-11-05 15:32
Hi @radekmie I thought initially this option was a solution that exists on the market ...Thanks for clarification!
