### ISSUE TITLE
uniforms-antd NumFields

### ISSUE THREAD

**Issue by pdubs-tl** [vazco/uniforms#447] opened 2018-07-09 04:15 UTC
I'm having an issue with antd theming for uniforms. Chrome seems to be rendering the NumField differently compared to other fields being used.

The field on the left in the image is being called using TextField, the one on the right is AutoField. The same issue occurs when using NumField.

<img width="550" alt="field problem" src="https://user-images.githubusercontent.com/36868598/42430401-52d59ba6-8382-11e8-9408-afdb5574111f.png">

I can currently substitute it by using the TextField to make things look uniform but any help is appreaciated.

**Comment by radekmie** [comment] 2018-07-23 09:08
Hi @pdubs-tl. Can you provide a small runnable reproduction? Or at least post the component tree for both?

**Comment by pdubs-tl** [comment] 2018-07-26 05:36
I'm not 100% sure how to extract that data from Webstorm, and wouldn't be able to build a small example at the moment.

I can share that we're currently implementing it this way:

`
import AutoField from 'uniforms-antd/AutoField';
import AutoForm from 'uniforms-antd/AutoForm';
import NumField from 'uniforms-antd/NumField';

                            <NumField
                                name="financialYearProfitBeforeTax"
                                step={0.01}
                                precision={2}
                                formatter={(value: number) => `$${value}`}
                            />
                            <NumField
                                name="financialYearSales"
                                step={0.01}
                                precision={2}
                                formatter={(value: number) => `$${value}`}
                            />
                            <NumField
                                prefix={<Icon type="calendar" />}
                                name="financialYearInvoiceMonthly"
                                precision={0}
                            />
`

**Comment by radekmie** [comment] 2018-07-31 18:10
I've tried it today. Both locally and on [uniforms.tools](https://uniforms.tools/), the `NumField` rendered by `AutoField` looks like the one on the left of your image.

**Comment by radekmie** [comment] 2018-08-06 19:13
No answer so far, closing.

**Closed by radekmie** 2018-08-06 19:13 UTC
Labels: bug
