### ISSUE TITLE
Configuring label and placeholder in schema

### ISSUE THREAD

**Issue by pavankramadugu** [vazco/uniforms#973] opened 2021-05-31 11:19 UTC
```
const schema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      uniforms: { placeholder: true }
    },
  },
};
```
This is not showing placeholder as email in the ui. Using bootstrap5 3.4.0

I also have another query,

```
import LongTextField from "uniforms-bootstrap5"
const schema = {
  type: 'object',
  properties: {
    email: {
      type: 'string',
      uniforms: { component: "LongTextField", placeholder: true }
    },
  },
};
```
The issue here is i'm getting this json from server LongTextField is coming as "LongTextField" so it's not loading the schema. how to approach this when we try to get schema dynamically from server. Due to this i'm unable to use custom comps.

**Comment by wadamek65** [comment] 2021-06-11 11:39
Hi @pavankramadugu , thanks for the issue report.

1. After some initial investigation, I think you want to set `uniforms.placeholder` property to a string, and pass a `placeholder={true}` prop in your component explicitly to make it show up. [Like in this example in the playground.](https://uniforms.tools/playground#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzNt5QyYfVigALHBgVQIyeBHqmQ0WgoDyAOwySkbhMyGCwrKDxaZBAfKAB3AAIAZSU8cygksIjaACYAIQglBQBzKAAKAB0fBITYxJS0jUzwyLLgKpqa7KUMJAT26s6a-HEwKD6k5yUfYpIOoYT6HyVOHAg8GD7gBPNaSxs7Bz6AcnhYeGOEgF95mqu5nyuASiqn0hAYGziAST9pqAAohAKI5Ajo3LQYOIfFhfEl6Ko8EpEGDgiBIdDYT4AGo8Iq0M7GOD3EDwFocFCqHA4eAwZy0MAAVhAVyAA) I think there might be some underlying issue/inconsistency in our code though about how the placeholder prop is handled but this will require further investigation. (@radekmie @Monteth pinging for visibility if one of you maybe already has the answer).
2. As for your second question, certainly there is no way to use a custom component out of the box in a schema that is fetched from external sources. A solution that might help is maybe to create a helper function which will help you derive the schema, something like this:

```ts
const CustomLongTextField = () => {}; // Your custom component
const deriveComponentsFromNames = (schema, componentMap) => {
  for (const property of Object.values(schema.properties)) {
    const componentName = property.uniforms?.component;
    if (componentMap[componentName]) {
      property.uniforms.component = componentMap[componentName];
    }
  }
}

deriveComponentsFromNames(yourSchema, { LongTextField: CustomLongTextField });
// yourSchema should now have all uniforms.component references to LongTextField replaced with the appropriate component
// Note this will only work on the first level of the schema, if you want to replace all possible fields then you have to run this recursively
```

**Comment by radekmie** [comment] 2021-06-18 12:14
Hi @pavankramadugu. So I looked into it and it really looks weird. I'm surprised how it works now and how we didn't notice that. Anyway, let's jump into an example:

```ts
const schema = {
  type: 'object',
  properties: {
    a1: { type: 'string', uniforms: { label: 'a' } },
    b1: { type: 'string', uniforms: { label: true } },
    c1: { type: 'string', uniforms: { label: false } },
    a2: { type: 'string', uniforms: { placeholder: 'a' } },
    b2: { type: 'string', uniforms: { placeholder: true } },
    c2: { type: 'string', uniforms: { placeholder: false } },
    d: { type: 'string' },
  },
};
```

Additionally, let's think of the two flags we have in the context: `label` and `placeholder`. (Their default values come from the form props, so we can say that's exactly it.)

Now, let's think about how it works and whether it's expected (correct):
* If the `label` in context is `false`, then no label is visible. That's OK.
* If the `placeholder` in context is `false`, then no placeholder is visible. That's also OK.
* Here we assume both `label` and `placeholder` are true.
    1. The `a1` has `a` label and no placeholder. That's incorrect, the placeholder is missing.
    2. The `b1` has no label and placeholder. We would expect `B 1` as a placeholder here?
    3. The `c1` has no label and placeholder. That's about right, as the placeholder defaults to the label value, but maybe it shouldn't?
    4. The `a2` has `A 2` label and `a` placeholder. That's OK.
    5. The `b2` has `B 2` label and no placeholder. That's incorrect, the placeholder is missing.
    6. The `c2` has `C 2` label and no placeholder. That's OK.
    7. The `d` has `D` label and no placeholder. That's incorrect, the placeholder is missing.

Now, I've played around with it and my change is as follows:
```diff
 function propagate(
   prop: ReactNode,
   schema: ReactNode,
   state: boolean,
   fallback: ReactNode,
 ): [ReactNode, ReactNode] {
   const forcedFallbackInProp = prop === true || prop === undefined;
   const forcedFallbackInSchema = schema === true || schema === undefined;
 
-  const schemaValue = forcedFallbackInSchema ? fallback : schema;
+  const schemaValue = forcedFallbackInSchema ? fallback : schema || '';
   const value =
     prop === '' ||
     prop === false ||
     prop === null ||
-    (forcedFallbackInProp && (forcedFallbackInSchema || !state))
+    (forcedFallbackInProp && !state)
       ? ''
       : forcedFallbackInProp
       ? schemaValue
       : prop;
 
   return [value, schemaValue];
 }
```

Then it looks like it:
* Here we assume both `label` and `placeholder` are true.
    1. The `a1` has `a` in both label and placeholder. That's about right, as the placeholder defaults to the label value, but maybe it shouldn't?
    2. The `b1` has no label and placeholder. We would expect `B 1` as a placeholder here?
    3. The `c1` has no label and placeholder. That's about right, as the placeholder defaults to the label value, but maybe it shouldn't?
    4. The `a2` has `A 2` label and `a` placeholder. That's OK.
    5. The `b2` has `B 2` in both label and placeholder. That's OK.
    6. The `c2` has `C 2` label and no placeholder. That's OK.
    7. The `d` has `D` in both label and placeholder. That's OK.

What do you think? It'd be a breaking change to change it, but I'm not even sure whether it's better. It looks better, as the `uniforms` property should be merged with props, thus both `label` and `placeholder` in schema should be the same as in props.

**Comment by radekmie** [comment] 2021-07-10 13:07
I'd like to move on with this problem. @Monteth, @wadamek65, @kestarumper - could you take a look at my comment above and add your thoughts? If possible, I'd love to hear @pavankramadugu feedback too.

**Comment by wadamek65** [comment] 2021-07-12 12:42
@radekmie IMO both label and placeholder logic should not be intertwined anywhere and one should not be derived from the other. I think they both serve different purposes and should be handled separately. Of course, there are some cases where the placeholder is at the same time the label (some MUI inputs) but this should rather be an exception than a rule. 

So at the very least, this doesn't feel right to me. I would expect only a label and no placeholder.

> a1: { type: 'string', uniforms: { label: 'a' } },
> The a1 has a in both label and placeholder. That's about right, as the placeholder defaults to the label value, but maybe it shouldn't?

I'm thinking that to make the behaviors and API more clear/predictable maybe it would make sense if we only accepted strings and not booleans anymore? I can't really see a use case where I would want the schema property to show up as a label. Or maybe move it to a schema/field-level property like `deriveLabels`? These are my thoughts.

**Comment by Monteth** [comment] 2021-07-14 11:21
I agree with @wadamek65. I don't get why we expect a placeholder to be derived from a label. After the quick consideration, I would say the boolean value doesn't make much sense here (especially for a placeholder),  so it may be a good point to make this API easier to understand by removing the boolean.

**Comment by radekmie** [comment] 2021-12-10 10:56
_(We've had a team discussion about this issue, and here are the notes.)_

We've decided to implement it in v4, including these breaking changes:
* We'll remove the `placeholder` fallback at all.
    * That also means we'll get rid of the `placeholder` property in the context.
* We'll look into removing the fallback of `label` as well. It just needs to be confirmed whether or not projects are actually using that.
    * The default `label` retrieved from the schema should stay, as it's enough in most cases.

**Comment by BudgieInWA** [comment] 2022-04-15 04:35
I found this issue because I was surprised that adding `placeholder` to the schema had effect on its own, without adding `placeholder` to the `AutoForm` or `AutoField`. I am sharing my thoughts here in case it informs your design of the new placeholder API.

In my usecase, I want to use placeholders to show the format of the expected value, or to show the default value, not as a label. So a "Mobile Number" field might have a placeholder "0412 345 678" to show that I expect a local Australian phone number, and a "Filter" field might have a placeholder "Any" to show that a blank input means no filtering.

I am happy with `placeholder: true` meaning "use the label", because it has no pre-existing expected behaviour, so it doesn't get in the way. For my usecase, "use the default value" would be a more useful shortcut, but I can live without it.

I think it should at least be documented at https://uniforms.tools/docs/api-fields/#common-props and other places, that you need `placeholder` on the `AutoForm` or `AutoField` for placeholders to show up at all.

**Comment by radekmie** [comment] 2022-04-20 08:22
> For my usecase, "use the default value" would be a more useful shortcut, but I can live without it.

It does make sense in some cases, but I think the default value's meaning is "different enough" to not use it as a placeholder in general.

> I think it should at least be documented at https://uniforms.tools/docs/api-fields/#common-props and other places, that you need `placeholder` on the `AutoForm` or `AutoField` for placeholders to show up at all.

That's a very good point!

**Comment by Monteth** [comment] 2022-09-02 12:15
We had a planning session for uniforms@4, and we extended the plan from [this comment](https://github.com/vazco/uniforms/issues/973#issuecomment-990868781). 

To sum it up, we decided to:
- Remove the `placeholder` property from the form and context.
  - You can still specify it explicitly in field props.
- Remove the `label` from the form and context.
  - You can still specify it explicitly in field props, or it can be inferred (details in the next point).
- Add `provideDefaultLabelFromFieldName` as a bridge constructor parameter - it will enable label inferration from the schema.
- Change types of `placeholder` and `label` in fields to `?: string`, and - depending on the theme - the label could be the `?: ReactNode` type.

Our main motivation was to simplify the API, make it more predictable and self-describing (hence `provideDefaultLabelFromFieldName`).

**Closed** 2023-06-05 12:04 UTC
Labels: Type: Feature, Area: Core
