### ISSUE TITLE
BaseField shouldUpdate with isEqual causing infinite loops

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#652] opened 2019-11-21 10:54 UTC
I'm running into a weird bug when using uniforms together with Cypress, where the `isEqual` call in `BaseField` appears to cause an infinite loop which crashes the test runner.

https://github.com/vazco/uniforms/blob/008ba5be2aa43ec4592f1c052560330cdd111d9e/packages/uniforms/src/BaseField.tsx#L101

The way this happens is I'm passing an `icon` prop to `ListDelField`, and therefore the `isEqual` call starts digging really deep into the react component's FiberNode tree (a very long linked list) which leads to this loop. I guess that at some point it stops making recursive calls to `equalObjects`, but for some other reason it rerenders and starts comparing the 2 props again, freezing the browser (this is my guess).

Here's just an example showing a sample huge call stack. Shouldn't we use shallow equal instead to compare props? Or is there otherwise a way for me to change `BaseField`'s behavior without forking uniforms?

![out](https://user-images.githubusercontent.com/10428082/69331666-78672300-0c55-11ea-9fe6-dca1d39881db.gif)

**Comment by Floriferous** [comment] 2019-11-21 12:34
I guess we could leave the other `isEqual` calls, since this library controls its own state and field values, so you know the upper-bound of those comparisons. However you can't control what props are passed to each individual component, leading to potential performance issues like this. 

I checked and switching to shallow equal does fix my issue.

Happy to make a PR if this makes sense?

**Comment by radekmie** [comment] 2019-11-27 08:23
Hi @Floriferous. Indeed, we shouldn't force users to make their props acyclic. The thing I'm just concerned about is that I'm shocked no one actually had this problem before! I'm using this library for _quite_ a long time myself, and I'm passing components as props pretty often. I'll have to check it.

Aside from that: this was a deep equality check mostly because of the way how `AutoField` worked up to some point (passing down all props, not only the provided ones) - maybe it's not really needed anymore?

**Comment by radekmie** [comment] 2019-11-27 14:48
@Floriferous could you reproduce it somewhere when I could take a look at it? It works for me in most cases and I'm just curious if there's something I'm doing differently (or it's a problem at a bigger scale).

In the meantime, you can work around this issue with _disabling_ this check with `X.prototype.shouldComponentUpdate  = () => true;`. It's also worth noting that there's no sCU in v3.

**Comment by Floriferous** [comment] 2019-11-27 15:00
Have been unable to extract a reproduction so far, but our workaround is ok for now.

How far along is v3?

**Comment by radekmie** [comment] 2019-11-27 21:38
An actual final v3? Far away. An alpha? Most probably this week. A _semi-stable_ beta? No idea, definitely not this year.

**Comment by radekmie** [comment] 2019-12-04 16:51
There's an actual workaround for now and it's no longer a problem in v3. I'm closing.

**Closed by radekmie** 2019-12-04 16:51 UTC
Labels: enhancement
