### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `decimal`.

### ISSUE THREAD

**Issue by cunneen** [vazco/uniforms#677] opened 2020-01-02 02:34 UTC
Browser warnings for number types.

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1751645/71649620-5def9180-2d4b-11ea-8893-592279b67ae3.png">

### Reproduction

Using simple-schema-2 bridge and bootstrap-3

```js
import SimpleSchema from 'simpl-schema';
import SimpleSchema2Bridge from 'uniforms-bridge-simple-schema-2';
import { AutoForm } from 'uniforms-bootstrap3';
import React, { Component } from 'react';
import * as ReactDOM from 'react-dom';

const ss = new SimpleSchema({
  betterNumber: {
    type: Number,
    min: 5,
    max: 50
  }
});

const bridge = new SimpleSchema2Bridge(ss);

const App = () => {
  return (
    <div className="container">
      <AutoForm schema={bridge} onSubmit={console.log} />

    </div>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by kestarumper** [comment] 2020-01-08 16:23
Hi @cunneen,
I wasn't able to reproduce it using code sandbox and on our online [playground](https://uniforms.tools/playground#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoBlASwFswAbKQgYwAspSBDAShABpwIB7MGZUEwCu8bjCYA3KMgBmTCnE7DR4qQBEoFJgE9kARgAMBzumLiARlXSz5ikFvObk8CEKidKTGlDrcK6KAgbBXcQGHpGJmQQADsoAHdcEnIqWgZmfGAAHRjcXEd4eECAOSFSRwgkXGzcvNx4bTAoKtLywPYcutxSYhiqgFYO2rzmAA8Bg07cAF8c6bZOGF94gEkYil6oAFEIHiCkORClGG0YmgB5GMIhcx7EA9tQphOzy4A1eWJ0JiLguGnOPB0tIUOZuNx4DAXEwwABmEDTIA). Here is [CodeSandbox reproduction](https://codesandbox.io/s/uniforms-codesandbox-1p3gu) with **latest version of uniforms**. Which versions have you used?

**Comment by kestarumper** [comment] 2020-01-17 09:55
I'm closing this issue for now since I couldn't reproduce it. Feel free to ask for more help or reopen this issue in the future if anything similar happens.

**Closed by kestarumper** 2020-01-17 09:55 UTC
Labels: bug
