### ISSUE TITLE
Multiselect with checkboxes validation issue 

### ISSUE THREAD

**Issue by mattscooter** [vazco/uniforms#113] opened 2016-10-16 13:14 UTC
I am currently evaluating uniforms for my project and I've run into a problem with multiselect checkbox using the bootstrap 3 library.

In my schema I have a field defined as a String Array with allowed values of "one", "two", "three".  I want to be able to select multiple options.

```
multiselect: {
    type: [String],
    label: 'Multi Select',
    minCount: 1,
    allowedValues: ["one","two","three"],    
}
```

I am using an autoform and autofield and I haven't specified any additional properties.

The field is correctly being rendered as a multiselect with check boxes for each option, however when I submit the form I am getting a validation error saying that the field must be an array.  

I also tried getting rid of the allowed values and just use the uniforms: options in the field definition hoping it would make a difference:

```
  multiselect: {
    type: [String],
    label: 'Multi Select',
    minCount: 1,    
    uniforms: {
      options: [{ label: "supplier", value: "sup"}, {label: "client", value:"cli"},{label: "other", value:"oth"}],
    }
```

This time the fields appear to render correctly with the correct labels, however I am still getting the same error - "Multi Select must be an array".

Am I doing something wrong or is the component not mapping the data for the field correctly?  Do I need to do a custom transform on the data to make it an array?  If so, how?

**Comment by radekmie** [comment] 2016-10-16 13:30
I've never tried `minCount` with a multiselect, maybe that's an issue... Just let me know, which version are you using and I'll try to find out what is going on here.

**Comment by radekmie** [comment] 2016-10-16 13:37
I've tried it in `v1.2.0-rc.1` and it's working. The only issue is, that the returned value have an additional `null` as a first element - it's caused by `minCount`. Could you share some more of your code?

**Comment by mattscooter** [comment] 2016-10-16 14:31
I am currently using 1.1.5. 

It turns out that I was editing an entry that was created before I changed the schema to an array and it only had a string stored in the collection for that field.  That appears to have caused the field must be an array error.   So sorry for the confusion on that one.  It's getting late here. 

Now that I have realised my mistake and I'm working with the correct data I am seeing the same thing you have outlined.  That includes the  additional ```null```  as the first element in the array being stored.  

What I was hoping to do is make the field mandatory, i.e the user must select at least one option, hence the  ```minCount```.   I suspect the ```null``` is causing that validation to pass since there's it counts as an element.  So if the user has not selected anything the validation is letting the record be saved.

**Comment by radekmie** [comment] 2016-10-16 16:19
I've got two ideas on how to get rid of this `null`:

0. Pass `model={{multiselect: []}}` - it will bypass the `defaultValue` algorithm.
0. Use `autoValue` to filter out all `null`s _(and other invalid values)_.

**Comment by mattscooter** [comment] 2016-10-17 00:07
Thanks for the pointers...

1) This seems to be working as I expected.  I also did a test and it does't appear to interfere with setting defaults on other fields via the schema, which is good.  I will just have to remember this for  

2) ```autoValue``` didn't quite work as I would have hoped.  It didn't validate the empty selection and passed the data on to the backend causing an insert exception.  I could probaby catch this exception in the client when I am doing my real code, but with option 1 working as expected I will probably head down that path. 

So does this mean that the null item in the array is being introduced by simple schema or is it happening in the uniforms code somewhere?

**Comment by radekmie** [comment] 2016-10-17 05:08
[It's exactly here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L145).

**Comment by radekmie** [comment] 2016-10-17 18:11
OK, I think it's clear so I'm closing.

**Closed by radekmie** 2016-10-17 18:11 UTC
Labels: bug
