### ISSUE TITLE
React 17.x errors with AntD package

### ISSUE THREAD

**Issue by robertdavid010** [vazco/uniforms#694] opened 2020-03-18 18:47 UTC
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AutoValidatedQuickAntDForm, ErrorField, TextField
```

```
VM54198 modules.js:34912 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AutoValidatedQuickAntDForm
```

As React migrates away from class to functional components, many changes will probably require adopting new conventions etc. to the new APIs...

**Comment by radekmie** [comment] 2020-03-18 19:08
Duplicate of #690 and #605.

**Closed by radekmie** 2020-03-18 19:08 UTC
Labels: duplicate
