### ISSUE TITLE
Strange apostrophe rendering

### ISSUE THREAD

**Issue by dandv** [vazco/uniforms#726] opened 2020-05-20 02:02 UTC
The apostrophe used in the docs looks odd on Ubuntu 20 with Chromium 81:

![image](https://user-images.githubusercontent.com/33569/82396578-13716780-9a03-11ea-99a3-74bfa53887d7.png)

**Comment by Monteth** [comment] 2020-05-25 14:46
Hi, I have problems reproducing your bug. Can you provide more info about your system?  I.e. font name or other specific data would help.

**Comment by dandv** [comment] 2020-05-25 21:02
Hi, sorry for the scant bug report :) I had just installed Ubuntu 20. Probably an Ubuntu-specific problem. Feel free to close.

Page: https://uniforms.tools/docs/motivation
Browser: Chromium 83
Computed font: `system-ui, -apple-system, "Segoe UI", Roboto, Ubuntu, Cantarell, "Noto Sans", sans-serif, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`, via https://uniforms.tools/styles.39c250a1.css

![image](https://user-images.githubusercontent.com/33569/82842975-5d899b80-9e90-11ea-99ec-8180936b11e6.png)

**Comment by Monteth** [comment] 2020-05-26 08:54
Well, I also have Ubuntu 20 with chromium 83 on 2 machines, fonts also look the same, but my render is perfectly fine. 
@kestarumper I assume you have a similar environment, can u take a look here?

**Comment by kestarumper** [comment] 2020-05-27 10:24
I also have Ubuntu 20 (chrome `83.0.4103.61`) and it renders correctly.

**Comment by Monteth** [comment] 2020-06-10 10:53
Because of the inability to reproduce this bug, I'm closing this issue.

**Closed by Monteth** 2020-06-10 10:53 UTC
Labels: bug
