### ISSUE TITLE
Making a select field in Uniforms autocomplete

### ISSUE THREAD

**Issue by macsplan** [vazco/uniforms#402] opened 2018-03-28 01:35 UTC
Hi, reading the documentation, do you have any examples to connect a select field in Uniforms to do autocomplete?

So if I have an ajax request that fires onChange of the select field how could I connect it to the ajax call?

I'm guessing I add it tot the Schema but hooking it up is a bit confusing, any ideas?

**Comment by radekmie** [comment] 2018-04-05 12:57
Hi @macsplan. No, there's no such example. It's, in a way, duplicate of #151. The pattern stays the same - provide the data anyhow to your component as a prop.

A schema is not important here - you simply get your data and give it to the field. Based on the field value - you can get it for example from `onChange` - you ask the server for suggestions.

**Closed by radekmie** 2018-04-05 12:57 UTC
Labels: duplicate
