### ISSUE TITLE
Any OF Help Needed

### ISSUE THREAD

**Issue by pavankramadugu** [vazco/uniforms#996] opened 2021-08-12 11:56 UTC
If i want to implement any of similar to how it's in AnyOf section of this playground [https://rjsf-team.github.io/react-jsonschema-form/#](https://rjsf-team.github.io/react-jsonschema-form/#) is it possible ?

I want to show fields based on the condition if a thing is selected render specific fields.

Would appreciate the help. Thanks

**Comment by radekmie** [comment] 2021-08-13 14:59
Hi @pavankramadugu. Yes, it should be possible. However, keep in mind, that handling of `anyOf`/`allOf`/`oneOf` in uniforms is not ideal ([docs](https://uniforms.tools/docs/api-bridges#note-on-allofanyofoneof)).

The idea would be to have a field that is aware of your schema (through the `field` prop) and render different fields based on the selected `anyOf`/`allOf`/`oneOf`. Technically, it can keep the selected option in an internal state, and it'll work in the same way as the demo you've sent.

However, keep in mind, that in order to make this "variant selector" aware of the selected option when the user would open a pre-filled form (e.g., to edit something), you'll need to _somehow_ select the valid option. It's a harder problem, but can be solved by adding another field (e.g., `kind`, `type`, or `variant`), that says which option has the user chosen.

If you'll have something (not)working, definitely let us now!

**Comment by pavankramadugu** [comment] 2021-08-14 12:30
Understood a bit. can you give simple example schema for me to get what you meant in 2nd paragraph clearly

Would appreciate the help. Thanks

**Comment by pavankramadugu** [comment] 2021-08-17 13:24
Hi @radekmie I got it and implemented successfully. The another issue I am facing is, When i created a custom field Like this,
`const CustomField = (props) => {
      return( 'something' based on Props)
}

export default connectField(CustomField);
`
I am Using this custom field in the schema to render something by `{uniforms: {component: MyCustomField}}.` It's rendering fine but the data entered in this field is not being reflected in model like how it's being reflected if we make changes in any uniforms fields like LongTextField etc,

What am i missing here to get the data entered in the custom field to get in model ?? 

Btw i saw on your docs page where you created some custom fields like this [CycleField](https://uniforms.tools/docs/examples-custom-fields#cyclefield) here i can see that data you are modifying in this field is being reflected in model when i click on submit.

Can you let me know what i am missing in this case.
@radekmie @wadamek65

**Comment by wadamek65** [comment] 2021-08-17 15:06
@pavankramadugu Would you mind sharing the implementation of your component or even better a playground example with a reproduction of this behavior? Unfortunately, I am unsure of what could be causing your problems based on your description alone.

**Comment by pavankramadugu** [comment] 2021-08-18 05:42
@wadamek65 I got the issue after debugging in right way. I'm loving your component more each day. Awesome work @radekmie and You.

**Comment by radekmie** [comment] 2021-08-18 12:09
> Understood a bit. can you give simple example schema for me to get what you meant in 2nd paragraph clearly

I thought about something like this:
```ts
const schema = {
  title: 'Address',
  type: 'object',
  properties: {
    example: {
      oneOf: [
        { type: 'object', properties: { kind: { type: 'string', enum: ['variantA'] }, fieldA: { type: 'string' } } },
        { type: 'object', properties: { kind: { type: 'string', enum: ['variantB'] }, fieldB: { type: 'number' } } },
      ],
    },
  },
  required: [],
};
```

Then the `example.kind` field is the [_tag_ or _discriminator_](https://en.wikipedia.org/wiki/Tagged_union).

---

@pavankramadugu Could you elaborate a little on your problem and how you've solved it? It'd be best for other people that may encounter it.

**Comment by radekmie** [comment] 2021-09-13 21:09
It seems that the problem is already solved. I'll close it, but feel free to comment though.

**Closed by radekmie** 2021-09-13 21:09 UTC
Labels: question
