### ISSUE TITLE
Autoform onChangeModel no longer working?

### ISSUE THREAD

**Issue by mikkelking** [vazco/uniforms#1207] opened 2022-12-28 23:43 UTC
Uniforms 3.10.2 

The property onChangeModel is no longer called. There is reference made to it in #1083 which suggests that the property is somehow obsolete due to changes in the typing. The code omits the property, but it would still call it if present.

How do I get around this (short of reverting to an older version?) Is there some way to force the prop onto the object? (I am not using typescript)

**Comment by radekmie** [comment] 2022-12-29 08:18
Hi @mikkelking. Could you maybe provide a reproduction? This prop is not deprecated and #1083 only mentions the incorrect typings, which should not be a problem if you're not using TypeScript.

**Comment by mikkelking** [comment] 2022-12-30 06:42
@radekmie It's in a private repo - can I add you as a contributor so you can look at it?

**Comment by radekmie** [comment] 2022-12-30 10:14
I'd rather not, really. Use [our Codesandbox template](https://codesandbox.io/s/github/vazco/uniforms/tree/master/reproductions) and see if you can reproduce it there first.

**Comment by mikkelking** [comment] 2022-12-30 12:08
Of course the sandbox works perfectly. The problem is that I am building the schema dynamically from a definition file,  and reproducing the problem isn't easy without pretty much moving all of my code into the sandbox

I have the same problem with 3.10.1, 3.10.2 and 4.0 Alpha. It works ok in 3.10.0
I pulled up a github comparison here https://github.com/vazco/uniforms/compare/74cd15102ff1684934115a9a998a2e0862b6fdc8..37fa8c1e482cb9c3e8bd6e6395258634366b5d8a
but I can't see any changes that would impact the calling of the `onChangeModel` callback. 

But looking at https://github.com/vazco/uniforms/blob/1b4591a9c14e4c69cb08ca7fd37a886b6dbeee38/packages/uniforms/src/AutoForm.tsx#L26
I see this function, which appears to remove the `onChangeModel` function from the props
```
    getNativeFormProps() {
      const props = super.getNativeFormProps();
      return omit(props, ['onChangeModel']) as typeof props;
    }
```
I don't know when that is called, but might this be the problem?

**Comment by radekmie** [comment] 2023-01-02 09:46
Nope, the code you listed is correct - we don't want `onChangeModel` to be passed down to the native `<form>` element. The problem originates in #1170, as the `onChangeModel` is called in the callback of a `setState` call. But that means, your code relied on a bug then. Please check if the component is not unmounted too soon - it looks like it.

**Comment by radekmie** [comment] 2023-01-10 12:38
I'll close this one for now, but as soon as you'd have a reproduction, please post it here or in a new issue.

**Closed by radekmie** 2023-01-10 12:38 UTC
Labels: Type: Question
