### ISSUE TITLE
Disable prop from schema

### ISSUE THREAD

**Issue by aleksandrenko** [vazco/uniforms#289] opened 2017-05-14 15:09 UTC
Hello,
Is it possible to disable/skip a field from he schema?

`new SimpleSchema({
  firstName: {
    type: String
  },
  creationDate: {
        label: 'Created at',
        type: Date,
        autoValue: function () {
            if (this.isInsert) {
                return new Date;
            }
        },
        uniforms: {
          hidden: true
        }
  }
});`

**Comment by radekmie** [comment] 2017-05-14 16:04
Duplicate of #122. See [this comment](https://github.com/vazco/uniforms/issues/122#issuecomment-298179218).

**Closed by radekmie** 2017-05-14 16:04 UTC
Labels: duplicate
